### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Quantum-Codes** [Sid72020123/pyEventLogger#1]
Change format string from using square brackets to curly.
From `[file_name] [time]` to `{file_name} {time}`

If you do this, then you can use format functions to replace those with real values easily
`"{file_name} {time}".format(time="12:00", file_name="main.py")`

**Comment by Sid72020123** [comment]
I knew that already but I wanted square brackets. I don't want to change my code now...
I have exams. I won't add this idea. Sorry.
